wandb_version: 1

id:
  desc: null
  value: manifold_mixed_resnet
lr:
  desc: null
  value: 0.01
_wandb:
  desc: null
  value:
    python_version: 3.9.19
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1714592354.0
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 49
      - 51
      - 53
      - 55
      3:
      - 13
      - 16
      - 23
      - 61
      4: 3.9.19
      5: 0.16.6
      8:
      - 5
      - 13
      13: linux-x86_64
